<center> <h1> Scikit-Learn </h1> </center>

O [Scikit-Learn](scikit-learn.org/) é uma biblioteca de Ciência de dados para Python;

Ele possui mil e uma funcionalidades:
- Pré processar dados, normalizar, encodar, etc...
- Implementação dos principais algoritmos de IA (K-NN, árvores de decisão, Ranfom Forest, SVM, Naive Bayes, ...)
- Funções auxiliares:
    - Tunar hiper-parâmetros
    - Validação cruzada (veremos depois)
    - Diversas métricas
    - ...

Em geral, o Scikit-Learn segue uma mesmo API para a maioria das suas funções: .fit() e .predict()/.transform()

### .fit()

"Fitar" algo significa treinar ele, aprender algo, preparar o que vamos utilizar.

No caso de modelos de IA, se refere a treinar o modelo com os dados de treino (x_train, y_train)

No caso de uma normalização, significa "aprender" a média e o desvio padrão dos dados

### .predict() ou .transform()

O "predict()" significa predizer um conjunto de dados (x_test), resultando nas minhas predições/classes preditas (y_pred)

O transform é utilizado em coisas que não são exatamente predições - Por exemplo, normalizar os dados é uma "transformação", então após termos a média e o desvio padrão, podemos "transformar" um conjunto de dados

Vamos nessa aula ver um exemplo de como utilizar o scikit-learn para comparar um K-NN como uma árvore de decisão.

In [1]:
# Importar as bibliotecas padrões: Numpy e Pandas

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Vamos carregar um conjunto de dados já pronto - O iris
from sklearn.datasets import load_wine

In [4]:
data = load_wine()
df = pd.DataFrame(data.data, columns=data.feature_names) # dataframe
df["target"] = data.target

In [5]:
# Verificar o dataset
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [6]:
# Verificar por nulos
df.isna().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
target                          0
dtype: int64

In [9]:
# Breve descrição dos dados...
# Veremos mais na aula de EDA mas para deixar vocês curiosos ;)
df.describe().T

,count,mean,std,min,25%,50%,75%,max
alcohol,178.0,13.000618,0.811827,11.03,12.3625,13.050,13.6775,14.83
malic_acid,178.0,2.336348,1.117146,0.74,1.6025,1.865,3.0825,5.80
ash,178.0,2.366517,0.274344,1.36,2.2100,2.360,2.5575,3.23
alcalinity_of_ash,178.0,19.494944,3.339564,10.60,17.2000,19.500,21.5000,30.00
magnesium,178.0,99.741573,14.282484,70.00,88.0000,98.000,107.0000,162.00
total_phenols,178.0,2.295112,0.625851,0.98,1.7425,2.355,2.8000,3.88
flavanoids,178.0,2.029270,0.998859,0.34,1.2050,2.135,2.8750,5.08
nonflavanoid_phenols,178.0,0.361854,0.124453,0.13,0.2700,0.340,0.4375,0.66
proanthocyanins,178.0,1.590899,0.572359,0.41,1.2500,1.555,1.9500,3.58
color_intensity,178.0,5.058090,2.318286,1.28,3.2200,4.690,6.2000,13.00
hue,178.0,0.957449,0.228572,0.48,0.7825,0.965,1.1200,1.71
od280/od315_of_diluted_wines,178.0,2.611685,0.709990,1.27,1.9375,2.780,3.1700,4.00
proline,178.0,746.893258,314.907474,278.00,500.5000,673.500,985.0000,1680.00
target,178.0,0.938202,0.775035,0.00,0.0000,1.000,2.0000,2.00

In [ ]:
# Dividindo em X e y

In [10]:
X = df.drop(columns="target")
y = df["target"]

In [16]:
X

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [ ]:
# Dividindo os dados em Treino e teste

In [14]:
from sklearn.model_selection import train_test_split

In [44]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [48]:
x_test.shape

(54, 13)

In [ ]:
# Importando uma árvore de decisão

In [26]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
# Instanciando a árvore

In [28]:
model = DecisionTreeClassifier()

In [29]:
# Treinando ela

In [30]:
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
# Predizendo os valores

In [31]:
y_preds = model.predict(x_test)

In [33]:
y_preds

array([2, 0, 2, 1, 0, 0, 2, 1, 2, 2, 2, 2, 0, 0, 2, 2, 0, 0, 2, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 2, 0, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 2, 0,
       2, 2, 0, 2, 1, 1, 1, 1, 1, 2])

In [34]:
y_test

140    2
30     0
146    2
90     1
31     0
42     0
175    2
67     1
159    2
160    2
138    2
135    2
55     0
8      0
169    2
162    2
14     0
5      0
147    2
124    1
118    1
23     0
64     1
37     0
35     0
113    1
17     0
12     0
122    1
20     0
154    2
45     0
61     1
9      0
34     0
96     1
152    2
21     0
0      0
7      0
46     0
2      0
166    2
15     0
145    2
174    2
6      0
139    2
65     1
75     1
99     1
70     1
120    1
130    2
Name: target, dtype: int64

In [ ]:
# Verificando a acurácia

In [35]:
from sklearn.metrics import accuracy_score

In [36]:
accuracy_score(y_test, y_preds)

0.9814814814814815

In [ ]:
# Agora um K-NN:

In [45]:
from sklearn.neighbors import KNeighborsClassifier
# import perceptron

model_knn = KNeighborsClassifier(n_neighbors=5)

#model_perceptron = perceptron()

model_knn.fit(x_train, y_train)
y_preds = model_knn.predict(x_test)
accuracy_score(y_test, y_preds)

0.7037037037037037

Como melhor o K-NN? normalizando!

In [46]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
x_train = ss.fit_transform(x_train)
x_test = ss.transform(x_test)

model_2 = KNeighborsClassifier()
model_2.fit(x_train, y_train)
y_preds = model_2.predict(x_test)

accuracy_score(y_test, y_preds)

0.9259259259259259

Vão poder praticar mais com os exercícios liberados depois :)